import type { ProviderSecretName } from "./env";
import type { CachePolicy } from "./utils/http";

export type ProviderKind = "debug-grid" | "remote-xyz" | "r2-xyz" | "pmtiles-r2";
export type SourceKind = ProviderKind;
export type SourceFormat = "raster" | "vector";

export type DebugGridProvider = {
  kind: "debug-grid";
};

export type RemoteXyzProvider = {
  kind: "remote-xyz";
  template: string;
  secretPlaceholders?: Record<string, ProviderSecretName>;
  requestHeaders?: Record<string, string>;
};

export type R2XyzProvider = {
  kind: "r2-xyz";
  r2KeyTemplate: string;
};

export type PmtilesR2Provider = {
  kind: "pmtiles-r2";
  r2Key: string;
};

export type ProviderConfig =
  | DebugGridProvider
  | RemoteXyzProvider
  | R2XyzProvider
  | PmtilesR2Provider;

export type SourceTransform = {
  kind: "invert-raster";
};

export type BaseSource = {
  id: string;
  name: string;
  provider: ProviderConfig;
  format: SourceFormat;
  tileSize: number;
  minzoom: number;
  maxzoom: number;
  ext: string;
  attribution?: string;
  cachePolicy: CachePolicy;
  cacheTtlSeconds?: number;
  enabled?: boolean;
  transforms?: SourceTransform[];
  style?: Record<string, unknown>;
};

export type DebugGridSource = BaseSource & {
  provider: DebugGridProvider;
  format: "raster";
};

export type RemoteXyzSource = BaseSource & {
  provider: RemoteXyzProvider;
};

export type R2XyzSource = BaseSource & {
  provider: R2XyzProvider;
};

export type PmtilesR2Source = BaseSource & {
  provider: PmtilesR2Provider;
};

export type TileSource =
  | DebugGridSource
  | RemoteXyzSource
  | R2XyzSource
  | PmtilesR2Source;

export type SanitizedSource = Pick<
  TileSource,
  | "id"
  | "name"
  | "format"
  | "tileSize"
  | "minzoom"
  | "maxzoom"
  | "ext"
  | "attribution"
  | "cachePolicy"
> & {
  kind: ProviderKind;
  supportsTileJson: boolean;
  supportsGeneratedStyle: boolean;
};

export const SOURCES = {
  "debug-grid": {
    id: "debug-grid",
    name: "Debug Grid",
    provider: { kind: "debug-grid" },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 22,
    ext: "svg",
    attribution: "Generated by TileMux",
    cachePolicy: "ttl",
    cacheTtlSeconds: 31536000,
    enabled: true,
  },
  "osm-standard": {
    id: "osm-standard",
    name: "OpenStreetMap Standard",
    provider: {
      kind: "remote-xyz",
      template: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
      requestHeaders: {
        "User-Agent":
          "TileMux/0.0 (+https://github.com/the-Drunken-coder/TileMux)",
      },
    },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 19,
    ext: "png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>',
    cachePolicy: "respect-upstream",
    enabled: true,
  },
  "openmaps-opentopomap": {
    id: "openmaps-opentopomap",
    name: "OpenTopoMap",
    provider: {
      kind: "remote-xyz",
      template: "https://tile.openmaps.fr/opentopomap/{z}/{x}/{y}.png",
    },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 17,
    ext: "png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>, <a href="https://opentopomap.org/about">OpenTopoMap</a>, <a href="https://openmaps.fr/">openmaps.fr</a>',
    cachePolicy: "respect-upstream",
    enabled: true,
  },
  "openmaps-openhikingmap": {
    id: "openmaps-openhikingmap",
    name: "OpenHikingMap",
    provider: {
      kind: "remote-xyz",
      template: "https://tile.openmaps.fr/openhikingmap/{z}/{x}/{y}.png",
    },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 17,
    ext: "png",
    attribution:
      '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>, OpenHikingMap, <a href="https://openmaps.fr/">openmaps.fr</a>',
    cachePolicy: "respect-upstream",
    enabled: true,
  },
  "example-remote": {
    id: "example-remote",
    name: "Example Remote XYZ",
    provider: {
      kind: "remote-xyz",
      template:
        "https://example.com/tiles/{z}/{x}/{y}.{ext}?token={PROVIDER_TOKEN}",
      secretPlaceholders: {
        PROVIDER_TOKEN: "CUSTOM_PROVIDER_KEY",
      },
    },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 19,
    ext: "png",
    attribution: "Example provider",
    cachePolicy: "respect-upstream",
    enabled: false,
  },
  "local-r2": {
    id: "local-r2",
    name: "Local R2 Tiles",
    provider: {
      kind: "r2-xyz",
      r2KeyTemplate: "tiles/local-r2/{z}/{x}/{y}.{ext}",
    },
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 22,
    ext: "png",
    attribution: "Private tiles",
    cachePolicy: "ttl",
    cacheTtlSeconds: 31536000,
    enabled: true,
  },
  "pmtiles-r2-todo": {
    id: "pmtiles-r2-todo",
    name: "PMTiles R2 TODO",
    provider: {
      kind: "pmtiles-r2",
      r2Key: "pmtiles/example.pmtiles",
    },
    format: "vector",
    tileSize: 512,
    minzoom: 0,
    maxzoom: 14,
    ext: "mvt",
    attribution: "Private PMTiles",
    cachePolicy: "none",
    enabled: false,
  },
} as const satisfies Record<string, TileSource>;

export function isSourceEnabled(source: TileSource): boolean {
  return source.enabled !== false;
}

export function getSource(sourceId: string): TileSource | undefined {
  return Object.values(SOURCES).find((source) => source.id === sourceId);
}

export function getEnabledSource(sourceId: string): TileSource | undefined {
  const source = getSource(sourceId);
  return source && isSourceEnabled(source) ? source : undefined;
}

export function listEnabledSources(): TileSource[] {
  return Object.values(SOURCES).filter(isSourceEnabled);
}

export function sanitizeSource(source: TileSource): SanitizedSource {
  return {
    id: source.id,
    name: source.name,
    kind: source.provider.kind,
    format: source.format,
    tileSize: source.tileSize,
    minzoom: source.minzoom,
    maxzoom: source.maxzoom,
    ext: source.ext,
    attribution: source.attribution,
    cachePolicy: source.cachePolicy,
    supportsTileJson: source.provider.kind !== "pmtiles-r2",
    supportsGeneratedStyle: source.format === "raster" || Boolean(source.style),
  };
}
