import type { ProviderSecretName } from "./env";
import type { CachePolicy } from "./utils/http";

export type SourceKind = "debug-grid" | "remote-xyz" | "r2-xyz" | "pmtiles-r2";
export type SourceFormat = "raster" | "vector";

export type BaseSource = {
  id: string;
  name: string;
  kind: SourceKind;
  format: SourceFormat;
  tileSize: number;
  minzoom: number;
  maxzoom: number;
  ext: string;
  attribution?: string;
  cachePolicy: CachePolicy;
  cacheTtlSeconds?: number;
  enabled?: boolean;
  style?: Record<string, unknown>;
};

export type DebugGridSource = BaseSource & {
  kind: "debug-grid";
  format: "raster";
};

export type RemoteXyzSource = BaseSource & {
  kind: "remote-xyz";
  template: string;
  secretPlaceholders?: Record<string, ProviderSecretName>;
};

export type R2XyzSource = BaseSource & {
  kind: "r2-xyz";
  r2KeyTemplate: string;
};

export type PmtilesR2Source = BaseSource & {
  kind: "pmtiles-r2";
  r2Key: string;
};

export type TileSource =
  | DebugGridSource
  | RemoteXyzSource
  | R2XyzSource
  | PmtilesR2Source;

export type SanitizedSource = Pick<
  TileSource,
  | "id"
  | "name"
  | "kind"
  | "format"
  | "tileSize"
  | "minzoom"
  | "maxzoom"
  | "ext"
  | "attribution"
  | "cachePolicy"
> & {
  supportsTileJson: boolean;
  supportsGeneratedStyle: boolean;
};

export const SOURCES = {
  "debug-grid": {
    id: "debug-grid",
    name: "Debug Grid",
    kind: "debug-grid",
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 22,
    ext: "svg",
    attribution: "Generated by TileMux",
    cachePolicy: "ttl",
    cacheTtlSeconds: 31536000,
    enabled: true,
  },
  "example-remote": {
    id: "example-remote",
    name: "Example Remote XYZ",
    kind: "remote-xyz",
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 19,
    ext: "png",
    template: "https://example.com/tiles/{z}/{x}/{y}.{ext}?token={PROVIDER_TOKEN}",
    secretPlaceholders: {
      PROVIDER_TOKEN: "CUSTOM_PROVIDER_KEY",
    },
    attribution: "Example provider",
    cachePolicy: "respect-upstream",
    enabled: false,
  },
  "local-r2": {
    id: "local-r2",
    name: "Local R2 Tiles",
    kind: "r2-xyz",
    format: "raster",
    tileSize: 256,
    minzoom: 0,
    maxzoom: 22,
    ext: "png",
    r2KeyTemplate: "tiles/local-r2/{z}/{x}/{y}.{ext}",
    attribution: "Private tiles",
    cachePolicy: "ttl",
    cacheTtlSeconds: 31536000,
    enabled: true,
  },
  "pmtiles-r2-todo": {
    id: "pmtiles-r2-todo",
    name: "PMTiles R2 TODO",
    kind: "pmtiles-r2",
    format: "vector",
    tileSize: 512,
    minzoom: 0,
    maxzoom: 14,
    ext: "mvt",
    r2Key: "pmtiles/example.pmtiles",
    attribution: "Private PMTiles",
    cachePolicy: "none",
    enabled: false,
  },
} as const satisfies Record<string, TileSource>;

export function isSourceEnabled(source: TileSource): boolean {
  return source.enabled !== false;
}

export function getSource(sourceId: string): TileSource | undefined {
  return Object.values(SOURCES).find((source) => source.id === sourceId);
}

export function getEnabledSource(sourceId: string): TileSource | undefined {
  const source = getSource(sourceId);
  return source && isSourceEnabled(source) ? source : undefined;
}

export function listEnabledSources(): TileSource[] {
  return Object.values(SOURCES).filter(isSourceEnabled);
}

export function sanitizeSource(source: TileSource): SanitizedSource {
  return {
    id: source.id,
    name: source.name,
    kind: source.kind,
    format: source.format,
    tileSize: source.tileSize,
    minzoom: source.minzoom,
    maxzoom: source.maxzoom,
    ext: source.ext,
    attribution: source.attribution,
    cachePolicy: source.cachePolicy,
    supportsTileJson: source.kind !== "pmtiles-r2",
    supportsGeneratedStyle: source.format === "raster" || Boolean(source.style),
  };
}
